name: async_workshop
description: Asynchronous and multi-threading workshop for Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
